# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-24 15:41
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bangazon_api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PaymentType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('account_number', models.IntegerField()),
            ],
        ),
        migrations.AddField(
            model_name='customer',
            name='status',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='paymenttype',
            name='customer_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bangazon_api.Customer'),
        ),
    ]
