# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-24 18:49
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bangazon_api', '0003_merge_20170424_1848'),
    ]

    operations = [
        migrations.CreateModel(
            name='Computer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('purchased_date', models.DateField()),
                ('decommissioned_date', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('budget', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=55)),
                ('last_name', models.CharField(max_length=55)),
                ('supervisor', models.IntegerField()),
                ('computer_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bangazon_api.Computer')),
                ('department_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bangazon_api.Department')),
            ],
        ),
        migrations.CreateModel(
            name='Training',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateField()),
                ('name', models.CharField(max_length=55)),
                ('end_date', models.DateField()),
                ('max_attendees', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='TrainingSession',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('employee_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bangazon_api.Employee')),
                ('training_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bangazon_api.Training')),
            ],
        ),
    ]
